### ISSUE TITLE
Help & Guidance

### ISSUE THREAD

**Issue by andro101010** [lwsrbrts/PoSHive#11]
Hi,
I've been (hobby) working on some macOS/iOS swift code to interface with the Hive API but was stymied by the move to Beekeeper until I found your work. Thank you so much for your clear code.
Beekeeper actually seems easier to deal with than the old API but I wanted to ask : Is there any Beekeeper documentation available and if so where, or did you have to work all the calls out by trial and error?
Thanks again,
MattJohns

**Comment by lwsrbrts** [comment]
Hi @andro101010 - it was mostly trial and error and "reverse" engineering if I'm being honest, my main toolkit was using Dev Tools (F12) in Firefox - Chrome tends to crap out with a syntax error when it can't show a malformed response.

Basically I would log on to the hivehome website, hit F12 and then perform the actions I wanted. I would check the request and response body to see what was being sent and received and then try and work out what the logic was and repeat it in the code. Obviously it's all PowerShell code but with PSCore6 being open-sourced, the module will become very useful to everyone, no matter their platform.

Feel free to ask more - happy to help.

Cheers
Lewis
